package org.rdlinux.mssql;

import com.github.javafaker.Faker;
import org.junit.Assert;
import org.junit.Test;
import org.rdlinux.ezmybatis.core.EzQuery;
import org.rdlinux.ezmybatis.core.dao.JdbcInsertDao;
import org.rdlinux.ezmybatis.core.mapper.EzMapper;
import org.rdlinux.ezmybatis.core.sqlstruct.table.EntityTable;
import org.rdlinux.ezmybatis.core.sqlstruct.table.EzQueryTable;
import org.rdlinux.ezmybatis.demo.entity.BaseEntity;
import org.rdlinux.ezmybatis.demo.entity.ComplexDepartment;
import org.rdlinux.ezmybatis.demo.entity.ComplexUser;
import org.rdlinux.ezmybatis.demo.entity.ExtInfo;
import org.rdlinux.ezmybatis.demo.mapper.ComplexUserMapper;
import org.rdlinux.ezmybatis.expand.oracle.update.Merge;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.util.Random;
import java.util.UUID;

public class MsSqlComplexMergeTests extends MsSqlBaseTest {
    private static final Faker faker = new Faker(java.util.Locale.CHINA);

    private ComplexUser buildComplexUser() {
        ComplexUser user = new ComplexUser();
        user.setUsername(faker.name().fullName());
        user.setAge(new Random().nextInt(100));
        user.setUserType((short) 1);
        user.setScore(faker.number().randomNumber());
        user.setAccountBalance(faker.number().randomDouble(2, 0, 10000));
        user.setSalary(new BigDecimal(faker.number().randomDouble(2, 3000, 50000))
                .setScale(2, RoundingMode.DOWN));
        user.setIsActive(new Random().nextBoolean());

        ComplexUser.UserStatus[] statuses = ComplexUser.UserStatus.values();
        user.setStatus(statuses[new Random().nextInt(statuses.length)]);
        user.setBirthday(faker.date().birthday());
        user.setAvatar("binary_avatar_data".getBytes(StandardCharsets.UTF_8));
        user.setDescription(faker.lorem().paragraph());
        user.setSecretContent(faker.internet().password());
        user.setSpecificColumn("SpecificCol_Val");

        ExtInfo extInfo = new ExtInfo();
        extInfo.setHobby(faker.esports().game());
        extInfo.setRemark("Generated by DM merge test");
        user.setExtInfo(extInfo);

        user.setDepartmentId(UUID.randomUUID().toString().replaceAll("-", ""));
        return user;
    }

    private ComplexDepartment buildComplexDepartment() {
        ComplexDepartment dept = new ComplexDepartment();
        dept.setName(faker.company().name());
        dept.setParentId(UUID.randomUUID().toString().replaceAll("-", ""));
        dept.setDescription(faker.company().catchPhrase());
        return dept;
    }

    private String insertAndGetComplexUserId() {
        ComplexUser user = this.buildComplexUser();
        this.sqlSession.getMapper(ComplexUserMapper.class).insert(user);
        this.sqlSession.commit();
        return user.getId();
    }

    @Test
    public void mergeMatchedUpdateTest() {
        String userId = this.insertAndGetComplexUserId();
        EntityTable userTable = EntityTable.of(ComplexUser.class);
        EzQuery<ComplexUser> sourceQuery = EzQuery.builder(ComplexUser.class)
                .from(userTable)
                .select()
                .addAll()
                .done()
                .where()
                .addCondition(userTable.field(BaseEntity.Fields.id), userId)
                .done()
                .build();
        EzQueryTable sourceTable = EzQueryTable.of(sourceQuery);

        ComplexUser insertModel = this.buildComplexUser();
        insertModel.setId(userId);

        Merge merge = Merge.into(userTable)
                .using(sourceTable)
                .on()
                .addCondition(userTable.field(BaseEntity.Fields.id), sourceTable.column("ID"))
                .done()
                .set()
                .add(userTable.field(ComplexUser.Fields.username).set("dm_merge_update_name"))
                .add(userTable.field(ComplexUser.Fields.age).set(35))
                .done()
                .whenNotMatchedThenInsert(insertModel)
                .build();

        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        Integer ret = mapper.expandUpdate(merge);
        this.sqlSession.commit();
        Assert.assertNotNull(ret);

        ComplexUser updated = mapper.selectById(ComplexUser.class, userId);
        Assert.assertNotNull(updated);
        Assert.assertEquals("dm_merge_update_name", updated.getUsername());
        Assert.assertEquals(Integer.valueOf(35), updated.getAge());
    }

    @Test
    public void mergeNotMatchedInsertTest() {
        JdbcInsertDao jdbcInsertDao = new JdbcInsertDao(this.sqlSession);
        ComplexDepartment department = this.buildComplexDepartment();
        jdbcInsertDao.insert(department);

        EntityTable departmentTable = EntityTable.of(ComplexDepartment.class);
        EzQuery<ComplexDepartment> sourceQuery = EzQuery.builder(ComplexDepartment.class)
                .from(departmentTable)
                .select()
                .addAll()
                .done()
                .where()
                .addCondition(departmentTable.field(BaseEntity.Fields.id), department.getId())
                .done()
                .build();
        EzQueryTable sourceTable = EzQueryTable.of(sourceQuery);

        EntityTable userTable = EntityTable.of(ComplexUser.class);
        ComplexUser user = this.buildComplexUser();
        user.setDepartmentId(department.getId());
        user.setUsername("dm_merge_insert_name");
        user.setAge(28);
        user.setStatus(ComplexUser.UserStatus.NORMAL);


        Merge merge = Merge.into(userTable)
                .using(sourceTable)
                .on(o ->
                        o.addCondition(userTable.field(ComplexUser.Fields.departmentId).eq(sourceTable.column("id"))))
                .set(s ->
                        s.add(userTable.field(ComplexUser.Fields.username).set("dm_merge_should_not_update")))
                .whenNotMatchedThenInsert(user)
                .build();
        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        Integer ret = mapper.expandUpdate(merge);
        this.sqlSession.commit();
        Assert.assertNotNull(ret);

        ComplexUser inserted = mapper.selectById(ComplexUser.class, user.getId());
        Assert.assertNotNull(inserted);
        Assert.assertEquals(user.getId(), inserted.getId());
        Assert.assertEquals("dm_merge_insert_name", inserted.getUsername());
        Assert.assertEquals(department.getId(), inserted.getDepartmentId());
        Assert.assertEquals(Integer.valueOf(28), inserted.getAge());
        Assert.assertEquals(ComplexUser.UserStatus.NORMAL, inserted.getStatus());
    }
}
