package org.rdlinux.oracle;

import com.github.javafaker.Faker;
import lombok.extern.slf4j.Slf4j;
import org.junit.Assert;
import org.junit.Test;
import org.rdlinux.ezmybatis.core.EzQuery;
import org.rdlinux.ezmybatis.core.dao.JdbcInsertDao;
import org.rdlinux.ezmybatis.core.mapper.EzMapper;
import org.rdlinux.ezmybatis.core.sqlstruct.Select;
import org.rdlinux.ezmybatis.core.sqlstruct.table.EntityTable;
import org.rdlinux.ezmybatis.demo.entity.*;
import org.rdlinux.ezmybatis.demo.mapper.ComplexUserMapper;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.*;

@Slf4j
public class OracleComplexEntityInsertTest extends OracleBaseTest {

    private static final Faker faker = new Faker(java.util.Locale.CHINA);

    private ComplexUser buildComplexUser() {
        ComplexUser user = new ComplexUser();
        // ID, createTime, updateTime 由 AbstractBaseTest 里的 Listener 自动处理
        user.setUsername(faker.name().fullName());
        user.setAge(new Random().nextInt(100));
        user.setUserType((short) 1);
        user.setScore(faker.number().randomNumber());
        user.setAccountBalance(faker.number().randomDouble(2, 0, 10000));
        user.setSalary(new BigDecimal(faker.number().randomDouble(2, 3000, 50000))
                .setScale(2, RoundingMode.DOWN));
        user.setIsActive(new Random().nextBoolean());

        ComplexUser.UserStatus[] statuses = ComplexUser.UserStatus.values();
        user.setStatus(statuses[new Random().nextInt(statuses.length)]);
        user.setBirthday(faker.date().birthday());
        user.setAvatar("binary_avatar_data".getBytes(StandardCharsets.UTF_8));
        user.setDescription(faker.lorem().paragraph());
        user.setIgnoredData("This should be transient");
        user.setSecretContent(faker.internet().password());

        ExtInfo extInfo = new ExtInfo();
        extInfo.setHobby(faker.esports().game());
        extInfo.setRemark("Generated by generic factory");
        user.setExtInfo(extInfo);

        user.setDepartmentId(UUID.randomUUID().toString().replace("-", ""));
        return user;
    }

    private ComplexDepartment buildComplexDepartment() {
        ComplexDepartment dept = new ComplexDepartment();
        dept.setName(faker.company().name());
        dept.setParentId(UUID.randomUUID().toString().replace("-", ""));
        dept.setDescription(faker.company().catchPhrase());
        return dept;
    }

    private ComplexOrder buildComplexOrder() {
        ComplexOrder order = new ComplexOrder();
        order.setUserId(UUID.randomUUID().toString().replace("-", ""));
        order.setOrderNo("ORD-" + System.currentTimeMillis() + "-" + new Random().nextInt(1000));
        order.setTotalAmount(new BigDecimal(faker.number().randomDouble(2, 10, 5000)));
        ComplexOrder.OrderStatus[] statuses = ComplexOrder.OrderStatus.values();
        order.setStatus(statuses[new Random().nextInt(statuses.length)]);
        return order;
    }

    private ComplexOrderItem buildComplexOrderItem() {
        ComplexOrderItem item = new ComplexOrderItem();
        item.setOrderId(UUID.randomUUID().toString().replace("-", ""));
        item.setProductId("PROD-" + faker.number().randomNumber());
        item.setQuantity(new Random().nextInt(10) + 1);
        item.setUnitPrice(new BigDecimal(faker.number().randomDouble(2, 5, 500)));
        item.setItemTotalAmount(item.getUnitPrice().multiply(new BigDecimal(item.getQuantity())));
        return item;
    }

    private List<ComplexUser> buildComplexUsers(int count) {
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < count; i++) {
            users.add(this.buildComplexUser());
        }
        return users;
    }

    private void preheat(EzMapper ezMapper) {
        for (int i = 0; i < 10; i++) {
            ezMapper.selectMapBySql("select 1 from dual", new HashMap<>());
        }
    }

    // =================================================================================================================
    // ComplexUserMapper Tests (EzBaseMapper)
    // =================================================================================================================

    @Test
    public void ezBaseMapperInsert() {
        // 测试 ComplexUserMapper 插入 ComplexUser
        ComplexUser user = this.buildComplexUser();
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).insert(user);

        // 测试 EzMapper 插入全部其他实体
        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        ret += mapper.insert(this.buildComplexDepartment());
        ret += mapper.insert(this.buildComplexOrder());
        ret += mapper.insert(this.buildComplexOrderItem());

        this.sqlSession.commit();
        Assert.assertEquals(4, ret);
        log.info("insert all entities ret: {}", ret);
    }

    @Test
    public void ezBaseMapperInsertByTable() {
        ComplexUser user = this.buildComplexUser();
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).insertByTable(EntityTable.of(ComplexUser.class), user);
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("ComplexUserMapper.insertByTable ret: {}", ret);
    }

    @Test
    public void ezBaseMapperBatchInsert() {
        List<ComplexUser> users = this.buildComplexUsers(2);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).batchInsert(users);

        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        List<ComplexDepartment> depts = Arrays.asList(this.buildComplexDepartment(), this.buildComplexDepartment());
        List<ComplexOrder> orders = Arrays.asList(this.buildComplexOrder(), this.buildComplexOrder());
        List<ComplexOrderItem> items = Arrays.asList(this.buildComplexOrderItem(), this.buildComplexOrderItem());

        ret += mapper.batchInsert(depts);
        ret += mapper.batchInsert(orders);
        ret += mapper.batchInsert(items);

        this.sqlSession.commit();
        Assert.assertEquals(8, ret);
        log.info("batchInsert all entities ret: {}", ret);
    }

    @Test
    public void ezBaseMapperBatchInsertByTable() {
        List<ComplexUser> users = this.buildComplexUsers(2);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).batchInsertByTable(EntityTable.of(ComplexUser.class), users);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("ComplexUserMapper.batchInsertByTable ret: {}", ret);
    }

    // =================================================================================================================
    // EzMapper Tests
    // =================================================================================================================

    @Test
    public void ezMapperInsert() {
        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        int ret = 0;
        ret += mapper.insert(this.buildComplexUser());
        ret += mapper.insert(this.buildComplexDepartment());
        ret += mapper.insert(this.buildComplexOrder());
        ret += mapper.insert(this.buildComplexOrderItem());

        this.sqlSession.commit();
        Assert.assertEquals(4, ret);
        log.info("EzMapper.insert all entities ret: {}", ret);
    }

    @Test
    public void ezMapperInsertByTable() {
        ComplexUser user = this.buildComplexUser();
        int ret = this.sqlSession.getMapper(EzMapper.class).insertByTable(EntityTable.of(ComplexUser.class), user);
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("EzMapper.insertByTable ret: {}", ret);
    }

    @Test
    public void ezMapperBatchInsert() {
        List<ComplexUser> users = this.buildComplexUsers(2);
        int ret = this.sqlSession.getMapper(EzMapper.class).batchInsert(users);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("EzMapper.batchInsert ret: {}", ret);
    }

    @Test
    public void ezMapperBatchInsertByTable() {
        List<ComplexUser> users = this.buildComplexUsers(2);
        int ret = this.sqlSession.getMapper(EzMapper.class).batchInsertByTable(EntityTable.of(ComplexUser.class), users);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("EzMapper.batchInsertByTable ret: {}", ret);
    }

    @Test
    public void ezMapperInsertBySql() {
        String sql = "INSERT INTO ez_complex_user (id, create_time, update_time, username, age, user_type, is_active, status, account_balance, salary) " +
                "VALUES ('#id', TO_DATE('2021-12-30 11:58:23', 'YYYY-MM-DD HH24:MI:SS'), " +
                "TO_DATE('2021-12-30 11:58:23', 'YYYY-MM-DD HH24:MI:SS'), " +
                "'DirectSqlUser', 27, 1, 1, 0, 99.99, 15000.00)\n";
        sql = sql.replace("#id", UUID.randomUUID().toString().replace("-", ""));
        int ret = this.sqlSession.getMapper(EzMapper.class).insertBySql(sql, new HashMap<>());
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("EzMapper.insertBySql ret: {}", ret);
    }

    @Test
    public void ezMapperInsertByQuery() {
        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        // 先插入一条种子订单数据，确保 SELECT 有结果可以被归档
        ComplexOrder seed = this.buildComplexOrder();
        mapper.insert(seed);

        // 构建查询：选取归档源表 (订单表) 中的记录，最多 1 条
        EntityTable orderTable = EntityTable.of(ComplexOrder.class);
        EzQuery<ComplexOrder> query = EzQuery.builder(ComplexOrder.class)
                .from(orderTable)
                .select(Select.EzSelectBuilder::addAll)
                .where(e -> e.add(orderTable.field(BaseEntity.Fields.id).eq(seed.getId())))
                .build();

        // 目标写入表设定为新建立的订单归档表：ez_complex_order_archive
        EntityTable archiveTargetTable = EntityTable.of(ComplexOrder.class, "EZ_COMPLEX_ORDER_ARCHIVE");

        int ret = mapper.insertByQuery(archiveTargetTable, query);
        this.sqlSession.commit();
        Assert.assertTrue(ret >= 0);
        log.info("EzMapper.insertByQuery (Archive Order) ret: {}", ret);
    }

    // =================================================================================================================
    // JdbcInsertDao Tests
    // =================================================================================================================

    @Test
    public void jdbcInsert() {
        JdbcInsertDao jdbcInsertDao = new JdbcInsertDao(this.sqlSession);
        int ret = 0;
        ret += jdbcInsertDao.insert(this.buildComplexUser());
        ret += jdbcInsertDao.insert(this.buildComplexDepartment());
        ret += jdbcInsertDao.insert(this.buildComplexOrder());
        ret += jdbcInsertDao.insert(this.buildComplexOrderItem());

        this.sqlSession.commit();
        Assert.assertEquals(4, ret);
        log.info("JdbcInsertDao.insert all entities ret: {}", ret);
    }

    @Test
    public void jdbcInsertByTable() {
        JdbcInsertDao jdbcInsertDao = new JdbcInsertDao(this.sqlSession);
        ComplexUser user = this.buildComplexUser();
        int ret = jdbcInsertDao.insertByTable(EntityTable.of(ComplexUser.class), user);
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("JdbcInsertDao.insertByTable ret: {}", ret);
    }

    @Test
    public void jdbcBatchInsert() {
        JdbcInsertDao jdbcInsertDao = new JdbcInsertDao(this.sqlSession);
        List<ComplexUser> users = this.buildComplexUsers(5);
        int ret = jdbcInsertDao.batchInsert(users);
        this.sqlSession.commit();
        Assert.assertEquals(5, ret);
        log.info("JdbcInsertDao.batchInsert ret: {}", ret);
    }

    @Test
    public void jdbcBatchInsertByTable() {
        JdbcInsertDao jdbcInsertDao = new JdbcInsertDao(this.sqlSession);
        List<ComplexUser> users = this.buildComplexUsers(5);
        int ret = jdbcInsertDao.batchInsertByTable(EntityTable.of(ComplexUser.class), users);
        this.sqlSession.commit();
        Assert.assertEquals(5, ret);
        log.info("JdbcInsertDao.batchInsertByTable ret: {}", ret);
    }

    // =================================================================================================================
    // Performance Tests
    // =================================================================================================================

    @Test
    public void ezMapperLoopInsertPerformanceTest() {
        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        this.preheat(mapper);
        long start = System.currentTimeMillis();
        for (int i = 0; i < 1; i++) {
            ComplexUser entity = this.buildComplexUser();
            mapper.insert(entity);
        }
        long end = System.currentTimeMillis();
        this.sqlSession.commit();
        Assert.assertTrue(end - start >= 0);
        log.info("ezMapperLoopInsertPerformanceTest cost: {}ms", end - start);
    }

    @Test
    public void ezMapperBatchInsertPerformanceTest() {
        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        this.preheat(mapper);
        long start = System.currentTimeMillis();
        for (int h = 0; h < 2; h++) {
            List<ComplexUser> models = new ArrayList<>(100);
            for (int i = 0; i < 5; i++) {
                models.add(this.buildComplexUser());
            }
            mapper.batchInsert(models);
        }
        long end = System.currentTimeMillis();
        this.sqlSession.commit();
        Assert.assertTrue(end - start >= 0);
        log.info("ezMapperBatchInsertPerformanceTest cost: {}ms", end - start);
    }

    @Test
    public void nativeJdbcBatchInsertPerformanceTest() throws SQLException {
        Connection connection = this.sqlSession.getConnection();
        String sql = "INSERT INTO ez_complex_user ( id, create_time, update_time, username, age, user_type, " +
                "score, account_balance, salary, is_active, status, birthday, " +
                "custom_column_name, secret_content, ext_info, department_id ) " +
                "VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )";

        long start = System.currentTimeMillis();
        for (int h = 0; h < 1; h++) {
            PreparedStatement statement = connection.prepareStatement(sql);
            EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
            this.preheat(mapper);
            for (int i = 0; i < 1; i++) {
                String id = UUID.randomUUID().toString().replace("-", "");
                // jdbc压测中由于走不到 AbstractBaseTest 的拦截器，所以此处原生语句需要提供时间和ID赋值
                statement.setString(1, id);
                statement.setTimestamp(2, new java.sql.Timestamp(System.currentTimeMillis()));
                statement.setTimestamp(3, new java.sql.Timestamp(System.currentTimeMillis()));
                statement.setString(4, "PerfUser_" + i);
                statement.setInt(5, 30);
                statement.setShort(6, (short) 1);
                statement.setLong(7, 100L);
                statement.setDouble(8, 99.99);
                statement.setBigDecimal(9, new BigDecimal("123.45"));
                statement.setBoolean(10, true);
                statement.setShort(11, (short) 0);
                statement.setDate(12, new java.sql.Date(System.currentTimeMillis()));
                statement.setString(13, "test_col");
                statement.setString(14, "ENCRYPTED::pass");
                statement.setString(15, "{\"hobby\":\"Coding\"}");
                statement.setString(16, "Dept01");
                statement.addBatch();
            }
            statement.executeBatch();
            statement.close();
        }
        connection.commit();
        connection.close();
        long end = System.currentTimeMillis();
        this.sqlSession.commit();
        Assert.assertTrue(end - start >= 0);
        log.info("nativeJdbcBatchInsertPerformanceTest cost: {}ms", end - start);
    }

    @Test
    public void jdbcInsertDaoBatchInsertPerformanceTest() {
        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        this.preheat(mapper);
        long start = System.currentTimeMillis();
        JdbcInsertDao jdbcBatchInsertDao = new JdbcInsertDao(this.sqlSession);
        for (int h = 0; h < 2; h++) {
            List<ComplexUser> models = new LinkedList<>();
            for (int i = 0; i < 5; i++) {
                models.add(this.buildComplexUser());
            }
            jdbcBatchInsertDao.batchInsert(models);
        }
        this.sqlSession.commit();
        long end = System.currentTimeMillis();
        Assert.assertTrue(end - start >= 0);
        log.info("jdbcInsertDaoBatchInsertPerformanceTest cost: {}ms", end - start);
    }
}
