package org.rdlinux.dm;

import com.github.javafaker.Faker;
import lombok.extern.slf4j.Slf4j;
import org.junit.Assert;
import org.junit.Test;
import org.rdlinux.ezmybatis.core.EzUpdate;
import org.rdlinux.ezmybatis.core.dao.JdbcUpdateDao;
import org.rdlinux.ezmybatis.core.mapper.EzMapper;
import org.rdlinux.ezmybatis.core.sqlstruct.CaseWhen;
import org.rdlinux.ezmybatis.core.sqlstruct.EntityField;
import org.rdlinux.ezmybatis.core.sqlstruct.Function;
import org.rdlinux.ezmybatis.core.sqlstruct.formula.Formula;
import org.rdlinux.ezmybatis.core.sqlstruct.table.EntityTable;
import org.rdlinux.ezmybatis.demo.entity.BaseEntity;
import org.rdlinux.ezmybatis.demo.entity.ComplexUser;
import org.rdlinux.ezmybatis.demo.entity.ExtInfo;
import org.rdlinux.ezmybatis.demo.mapper.ComplexUserMapper;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.util.*;

@Slf4j
public class DmComplexEntityUpdateTest extends DmBaseTest {

    private static final Faker faker = new Faker(java.util.Locale.CHINA);

    private ComplexUser buildComplexUser() {
        ComplexUser user = new ComplexUser();
        user.setUsername(faker.name().fullName());
        user.setAge(new Random().nextInt(100));
        user.setUserType((short) 1);
        user.setScore(faker.number().randomNumber());
        user.setAccountBalance(faker.number().randomDouble(2, 0, 10000));
        user.setSalary(new BigDecimal(faker.number().randomDouble(2, 3000, 50000))
                .setScale(2, RoundingMode.DOWN));
        user.setIsActive(new Random().nextBoolean());

        ComplexUser.UserStatus[] statuses = ComplexUser.UserStatus.values();
        user.setStatus(statuses[new Random().nextInt(statuses.length)]);
        user.setBirthday(faker.date().birthday());
        user.setAvatar("binary_avatar_data".getBytes(StandardCharsets.UTF_8));
        user.setDescription(faker.lorem().paragraph());
        user.setIgnoredData("This should be transient");
        user.setSecretContent(faker.internet().password());

        ExtInfo extInfo = new ExtInfo();
        extInfo.setHobby(faker.esports().game());
        extInfo.setRemark("Generated by generic factory for delete test");
        user.setExtInfo(extInfo);

        user.setDepartmentId(UUID.randomUUID().toString().replace("-", ""));
        return user;
    }

    private List<ComplexUser> buildComplexUsers(int count) {
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < count; i++) {
            users.add(this.buildComplexUser());
        }
        return users;
    }

    private String insertAndGetComplexUserId() {
        ComplexUser user = this.buildComplexUser();
        this.sqlSession.getMapper(ComplexUserMapper.class).insert(user);
        this.sqlSession.commit();
        return user.getId();
    }

    private List<String> insertAndGetComplexUserIds(int count) {
        List<ComplexUser> users = this.buildComplexUsers(count);
        this.sqlSession.getMapper(ComplexUserMapper.class).batchInsert(users);
        this.sqlSession.commit();
        List<String> ids = new LinkedList<>();
        for (ComplexUser user : users) {
            ids.add(user.getId());
        }
        return ids;
    }

    // ==========================================
    // EzBaseMapper Update Tests
    // ==========================================

    @Test
    public void ezBaseMapperUpdate() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        user.setUsername("王二_更新测试");
        user.setAge(27);
        user.setScore(9999L);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).update(user);
        this.sqlSession.commit();
        Assert.assertTrue(ret > 0);
        log.info("ezBaseMapperUpdate result: {}", ret);
    }

    @Test
    public void ezBaseMapperUpdateByTable() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        user.setAge(27);
        user.setSalary(BigDecimal.TEN);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class)
                .updateByTable(EntityTable.of(ComplexUser.class), user);
        this.sqlSession.commit();
        Assert.assertTrue(ret > 0);
        log.info("ezBaseMapperUpdateByTable result: {}", ret);
    }

    @Test
    public void ezBaseMapperBatchUpdate() {
        List<String> ids = this.insertAndGetComplexUserIds(3);
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < ids.size(); i++) {
            ComplexUser user = new ComplexUser();
            user.setId(ids.get(i));
            user.setUsername("更新者芳" + i);
            user.setAge(i + 20);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).batchUpdate(users);
        this.sqlSession.commit();
        Assert.assertTrue(ret != 0);
        log.info("ezBaseMapperBatchUpdate result: {}", ret);
    }

    @Test
    public void ezBaseMapperBatchUpdateByTable() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < ids.size(); i++) {
            ComplexUser user = new ComplexUser();
            user.setId(ids.get(i));
            user.setUsername("更新者芳" + i);
            user.setAge(i + 20);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class)
                .batchUpdateByTable(EntityTable.of(ComplexUser.class), users);
        this.sqlSession.commit();
        Assert.assertTrue(ret != 0);
        log.info("ezBaseMapperBatchUpdateByTable result: {}", ret);
    }

    @Test
    public void ezBaseMapperReplace() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        user.setUsername("王二_全量覆盖");
        user.setAge(56);
        user.setUserType((short) 2);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).replace(user);
        this.sqlSession.commit();
        Assert.assertTrue(ret > 0);
        log.info("ezBaseMapperReplace result: {}", ret);
    }

    @Test
    public void ezBaseMapperReplaceByTable() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        user.setUsername("王二_表量覆盖");
        user.setAge(27);
        user.setUserType((short) 2);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class)
                .replaceByTable(EntityTable.of(ComplexUser.class), user);
        this.sqlSession.commit();
        Assert.assertTrue(ret > 0);
        log.info("ezBaseMapperReplaceByTable result: {}", ret);
    }

    @Test
    public void ezBaseMapperBatchReplace() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < ids.size(); i++) {
            ComplexUser user = new ComplexUser();
            user.setId(ids.get(i));
            user.setUsername("全量覆芳" + i);
            user.setAge(i + 11);
            user.setUserType((short) 2);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).batchReplace(users);
        this.sqlSession.commit();
        Assert.assertTrue(ret != 0);
        log.info("ezBaseMapperBatchReplace result: {}", ret);
    }

    @Test
    public void ezBaseMapperBatchReplaceByTable() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < ids.size(); i++) {
            ComplexUser user = new ComplexUser();
            user.setId(ids.get(i));
            user.setUsername("全量覆芳" + i);
            user.setAge(i + 11);
            user.setUserType((short) 2);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class)
                .batchReplaceByTable(EntityTable.of(ComplexUser.class), users);
        this.sqlSession.commit();
        Assert.assertTrue(ret != 0);
        log.info("ezBaseMapperBatchReplaceByTable result: {}", ret);
    }

    // ==========================================
    // EzMapper Update Tests
    // ==========================================
    // (Omitted repetition for basic EzMapper standard updates, EzMapper calls use the identical routing to EzBaseMapper mostly)
    // We will still include a few standard tests to ensure the base EzMapper interface signatures are maintained.

    @Test
    public void ezMapperUpdate() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        user.setAge(27);
        int ret = this.sqlSession.getMapper(EzMapper.class).update(user);
        this.sqlSession.commit();
        Assert.assertTrue(ret > 0);
        log.info("ezMapperUpdate result: {}", ret);
    }

    @Test
    public void ezMapperBatchUpdate() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < ids.size(); i++) {
            ComplexUser user = new ComplexUser();
            user.setId(ids.get(i));
            user.setAge(i + 10);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(EzMapper.class).batchUpdate(users);
        this.sqlSession.commit();
        Assert.assertTrue(ret != 0);
        log.info("ezMapperBatchUpdate result: {}", ret);
    }

    @Test
    public void ezMapperReplace() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        user.setUsername("覆盖_EzMapper");
        user.setAge(1);
        int ret = this.sqlSession.getMapper(EzMapper.class).replace(user);
        this.sqlSession.commit();
        Assert.assertTrue(ret > 0);
        log.info("ezMapperReplace result: {}", ret);
    }

    @Test
    public void ezMapperBatchReplace() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < ids.size(); i++) {
            ComplexUser user = new ComplexUser();
            user.setId(ids.get(i));
            user.setUsername("全量覆芳" + i);
            user.setAge(i + 11);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(EzMapper.class).batchReplace(users);
        this.sqlSession.commit();
        Assert.assertTrue(ret != 0);
        log.info("ezMapperBatchReplace result: {}", ret);
    }

    @Test
    public void ezMapperUpdateByTable() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        user.setAge(27);
        int ret = this.sqlSession.getMapper(EzMapper.class)
                .updateByTable(EntityTable.of(ComplexUser.class), user);
        this.sqlSession.commit();
        Assert.assertTrue(ret > 0);
        log.info("ezMapperUpdateByTable result: {}", ret);
    }

    @Test
    public void ezMapperBatchUpdateByTable() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < ids.size(); i++) {
            ComplexUser user = new ComplexUser();
            user.setId(ids.get(i));
            user.setAge(i + 10);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(EzMapper.class)
                .batchUpdateByTable(EntityTable.of(ComplexUser.class), users);
        this.sqlSession.commit();
        Assert.assertTrue(ret != 0);
        log.info("ezMapperBatchUpdateByTable result: {}", ret);
    }

    @Test
    public void ezMapperReplaceByTable() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        user.setUsername("覆盖_EzMapper_ByTable");
        user.setAge(1);
        int ret = this.sqlSession.getMapper(EzMapper.class)
                .replaceByTable(EntityTable.of(ComplexUser.class), user);
        this.sqlSession.commit();
        Assert.assertTrue(ret > 0);
        log.info("ezMapperReplaceByTable result: {}", ret);
    }

    @Test
    public void ezMapperBatchReplaceByTable() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < ids.size(); i++) {
            ComplexUser user = new ComplexUser();
            user.setId(ids.get(i));
            user.setUsername("全量覆芳_ByTable" + i);
            user.setAge(i + 11);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(EzMapper.class)
                .batchReplaceByTable(EntityTable.of(ComplexUser.class), users);
        this.sqlSession.commit();
        Assert.assertTrue(ret != 0);
        log.info("ezMapperBatchReplaceByTable result: {}", ret);
    }

    // ==========================================
    // EzUpdate Lambda API Tests
    // ==========================================

    @Test
    public void ezUpdateByLambdaDSL() {
        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        EntityTable table = EntityTable.of(ComplexUser.class);
        String userId = this.insertAndGetComplexUserId();

        EzUpdate ezUpdate = EzUpdate.update(table)
                .set(s -> {
                    s.add(table.field(ComplexUser.Fields.username).set("Lambda Update API"));
                    // Conditional addition to the SET fragment
                    s.add(true, table.field(ComplexUser.Fields.age).set(99));
                })
                .where(w -> w.add(table.field(BaseEntity.Fields.id).eq(userId)))
                .build();

        int updated = mapper.ezUpdate(ezUpdate);
        this.sqlSession.commit();
        Assert.assertTrue(updated > 0);

        ComplexUser user = mapper.selectById(ComplexUser.class, userId);
        Assert.assertEquals("Lambda Update API", user.getUsername());
        Assert.assertEquals(Integer.valueOf(99), user.getAge());
        log.info("ezUpdateByLambdaDSL result: {}", updated);
    }

    @Test
    public void ezBatchUpdate() {
        List<EzUpdate> updates = new LinkedList<>();
        EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
        EntityTable table = EntityTable.of(ComplexUser.class);

        List<String> ids = this.insertAndGetComplexUserIds(2);

        EzUpdate ezUpdate1 = EzUpdate.update(table)
                .set(s -> s.add(table.field(ComplexUser.Fields.username).set("张碧澄_BATCH")))
                .where(w -> w.add(table.field(BaseEntity.Fields.id).eq(ids.get(0))))
                .build();
        updates.add(ezUpdate1);

        EzUpdate ezUpdate2 = EzUpdate.update(table)
                .set(s -> s.add(table.field(ComplexUser.Fields.username).set("张碧澄_BATCH2")))
                .where(w -> w.add(table.field(BaseEntity.Fields.id).eq(ids.get(1))))
                .build();
        updates.add(ezUpdate2);

        mapper.ezBatchUpdate(updates);
        this.sqlSession.commit();
        log.info("ezBatchUpdate executed completed");
    }

    @Test
    public void ezUpdateSetNullTest() {
        try {
            EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
            EntityTable table = EntityTable.of(ComplexUser.class);
            String uId = this.insertAndGetComplexUserId();

            EzUpdate ezUpdate = EzUpdate.update(table)
                    .set(s -> s.add(table.field(ComplexUser.Fields.departmentId).setToNull()))
                    .where(w -> w.add(table.field(BaseEntity.Fields.id).eq(uId)))
                    .build();
            mapper.ezUpdate(ezUpdate);
            this.sqlSession.commit();
        } catch (Exception e) {
            this.sqlSession.rollback();
            throw new RuntimeException(e);
        }
    }

    @Test
    public void ezUpdateFormulaTest() {
        try {
            EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
            EntityTable table = EntityTable.of(ComplexUser.class);
            String uId = this.insertAndGetComplexUserId();

            Formula scoreFormula = Formula.build(f ->
                    f.with(table.field(ComplexUser.Fields.score))
                            .addGroup(g ->
                                    g.with(table.field(ComplexUser.Fields.age)).subtract(5L))
                            .subtractGroup(g ->
                                    g.with(table.field(ComplexUser.Fields.age)).subtract(5L))
                            .divideGroup(g ->
                                    g.with(table.field(ComplexUser.Fields.age)).subtract(5L))
                            .multiplyGroup(g ->
                                    g.with(table.field(ComplexUser.Fields.age)).subtract(5L))
                            .add(1)
                            .subtract(1)
                            .multiply(1)
                            .divide(1)
                            .add(1)
            );
            Formula accountBalanceFormula = Formula.build(f ->
                    f.with(1)
            );
            EzUpdate ezUpdate = EzUpdate.update(table)
                    .set(s ->
                            s.add(table.field(ComplexUser.Fields.score).set(scoreFormula))
                                    .add(table.field(ComplexUser.Fields.accountBalance).set(accountBalanceFormula)))
                    .where(w -> w.add(table.field(BaseEntity.Fields.id).eq(uId)))
                    .build();
            int ret = mapper.ezUpdate(ezUpdate);
            this.sqlSession.commit();
            Assert.assertEquals(1, ret);
        } catch (Exception e) {
            this.sqlSession.rollback();
            throw new RuntimeException(e);
        }
    }

    @Test
    public void ezUpdateFunctionTest() {
        try {
            EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
            EntityTable table = EntityTable.of(ComplexUser.class);
            String uId = this.insertAndGetComplexUserId();
            // Function that sets age to either its existing age or 100, natively inside DB
            Function function = Function.builder("GREATEST").addArg(EntityField.of(table, ComplexUser.Fields.age))
                    .addArg(100).build();

            EzUpdate ezUpdate = EzUpdate.update(table)
                    .set(s -> s.add(table.field(ComplexUser.Fields.age).set(function)))
                    .where(w -> w.add(table.field(BaseEntity.Fields.id).eq(uId)))
                    .build();
            int ret = mapper.ezUpdate(ezUpdate);
            this.sqlSession.commit();
            Assert.assertEquals(1, ret);
        } catch (Exception e) {
            this.sqlSession.rollback();
            throw new RuntimeException(e);
        }
    }

    @Test
    public void ezUpdateCaseWhenTest() {
        try {
            EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
            EntityTable table = EntityTable.of(ComplexUser.class);
            String uId = this.insertAndGetComplexUserId();

            Function function = Function.builder("CONCAT")
                    .addArg(table.field(ComplexUser.Fields.username))
                    .addArg("-Modified").build();

            CaseWhen sonCaseWhen = CaseWhen.build(c -> c
                    .when(w -> w.add(table.field(ComplexUser.Fields.username).eq("张三1")), "李四")
                    .els("孙五"));

            CaseWhen caseWhen = CaseWhen.build(c -> c
                    .when(w -> w.add(table.field(ComplexUser.Fields.username).eq("源测试_张三_3")), "李四")
                    .when(w -> w.add(table.field(ComplexUser.Fields.username).eq("源测试_张三_4")), function)
                    .when(w -> w.add(table.field(ComplexUser.Fields.username).eq("源测试_张三_5")), sonCaseWhen)
                    .els(EntityField.of(table, ComplexUser.Fields.username)));

            EzUpdate ezUpdate = EzUpdate.update(table)
                    .set(s -> s.add(table.field(ComplexUser.Fields.username).set(caseWhen)))
                    .where(w -> w.add(table.field(BaseEntity.Fields.id).eq(uId)))
                    .build();
            int ret = mapper.ezUpdate(ezUpdate);
            this.sqlSession.commit();
            Assert.assertEquals(1, ret);
        } catch (Exception e) {
            this.sqlSession.rollback();
            throw new RuntimeException(e);
        }
    }

    @Test
    public void ezUpdateBySqlTest() {
        try {
            EzMapper mapper = this.sqlSession.getMapper(EzMapper.class);
            String id = this.insertAndGetComplexUserId();
            String sql = "update ez_complex_user set username = #{username} where id = #{id}";
            Map<String, Object> param = new HashMap<>();
            param.put("username", "SQL Direct Update Test");
            param.put("id", id);

            Integer result = mapper.updateBySql(sql, param);
            Assert.assertNotNull(result);
            Assert.assertTrue(result > 0);
            log.info("ezUpdateBySqlTest result: {}", result);
            this.sqlSession.commit();
        } catch (Exception e) {
            this.sqlSession.rollback();
            throw new RuntimeException(e);
        }
    }

    // ==========================================
    // jdbcUpdateDao Tests
    // ==========================================

    @Test
    public void jdbcUpdateDaoUpdate() {
        JdbcUpdateDao jdbcUpdateDao = new JdbcUpdateDao(this.sqlSession);

        List<ComplexUser> users = new LinkedList<>();
        List<String> ids = this.insertAndGetComplexUserIds(2);

        ComplexUser user1 = new ComplexUser();
        user1.setId(ids.get(0));
        user1.setUsername("王值_jdbcBatch");
        user1.setAge(12);
        users.add(user1);

        ComplexUser user2 = new ComplexUser();
        user2.setId(ids.get(1));
        user2.setUsername("李真_jdbcBatch");
        user2.setAge(19);
        users.add(user2);

        int ct = jdbcUpdateDao.batchUpdate(users);
        log.info("jdbcUpdateDaoUpdate batch result: {}", ct);

        ComplexUser singleUser = new ComplexUser();
        singleUser.setId(this.insertAndGetComplexUserId());
        singleUser.setUsername("王芳_jdbcSingle");
        singleUser.setAge(8);
        int sCt = jdbcUpdateDao.update(singleUser);
        Assert.assertTrue(sCt > 0);
        log.info("jdbcUpdateDaoUpdate single result: {}", sCt);
        this.sqlSession.commit();
    }

    @Test
    public void jdbcUpdateDaoPartialUpdate() {
        JdbcUpdateDao jdbcUpdateDao = new JdbcUpdateDao(this.sqlSession);

        ComplexUser user = new ComplexUser();
        user.setId(this.insertAndGetComplexUserId());
        user.setUsername("王芳_Partial");
        user.setAge(8);

        // partial update
        int sCt = jdbcUpdateDao.update(user, Arrays.asList(ComplexUser.Fields.username, ComplexUser.Fields.age));
        Assert.assertTrue(sCt > 0);
        log.info("jdbcUpdateDaoPartialUpdate single result: {}", sCt);

        List<ComplexUser> users = new LinkedList<>();
        List<String> ids = this.insertAndGetComplexUserIds(2);

        ComplexUser user1 = new ComplexUser();
        user1.setId(ids.get(0));
        user1.setUsername("王值_BatchPartial");
        user1.setAge(20);
        users.add(user1);

        ComplexUser user2 = new ComplexUser();
        user2.setId(ids.get(1));
        user2.setUsername("王值1_BatchPartial");
        user2.setAge(19);
        users.add(user2);

        int ct = jdbcUpdateDao.batchUpdate(users, Arrays.asList(ComplexUser.Fields.username, ComplexUser.Fields.age));
        log.info("jdbcUpdateDaoPartialUpdate batch result: {}", ct);
        this.sqlSession.commit();
    }

    @Test
    public void jdbcUpdateDaoReplace() {
        JdbcUpdateDao jdbcUpdateDao = new JdbcUpdateDao(this.sqlSession);

        List<ComplexUser> users = new LinkedList<>();
        List<String> ids = this.insertAndGetComplexUserIds(2);

        ComplexUser user1 = new ComplexUser();
        user1.setId(ids.get(0));
        user1.setUsername("王玉柱_JdbcRep");
        user1.setAge(12);
        user1.setStatus(ComplexUser.UserStatus.NORMAL);
        users.add(user1);

        ComplexUser user2 = new ComplexUser();
        user2.setId(ids.get(1));
        user2.setUsername("杨玉婷_JdbcRep");
        user2.setAge(18);
        users.add(user2);

        int ct = jdbcUpdateDao.batchReplace(users);
        log.info("jdbcUpdateDaoReplace batch result: {}", ct);

        ComplexUser singleUser = new ComplexUser();
        singleUser.setId(this.insertAndGetComplexUserId());
        singleUser.setUsername("王芳_JdbcRep");
        singleUser.setAge(8);
        int sCt = jdbcUpdateDao.replace(singleUser);
        Assert.assertTrue(sCt > 0);
        log.info("jdbcUpdateDaoReplace single result: {}", sCt);
        this.sqlSession.commit();
    }
}

