package org.rdlinux.pg;

import com.github.javafaker.Faker;
import lombok.extern.slf4j.Slf4j;
import org.junit.Assert;
import org.junit.Test;
import org.rdlinux.ezmybatis.core.EzDelete;
import org.rdlinux.ezmybatis.core.mapper.EzMapper;
import org.rdlinux.ezmybatis.core.sqlstruct.table.EntityTable;
import org.rdlinux.ezmybatis.demo.entity.*;
import org.rdlinux.ezmybatis.demo.mapper.ComplexUserMapper;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.util.*;

@Slf4j
public class PgComplexEntityDeleteTest extends PgBaseTest {

    private static final Faker faker = new Faker(java.util.Locale.CHINA);

    private ComplexUser buildComplexUser() {
        ComplexUser user = new ComplexUser();
        // ID, createTime, updateTime 由 AbstractBaseTest 里的 Listener 自动处理
        user.setUsername(faker.name().fullName());
        user.setAge(new Random().nextInt(100));
        user.setUserType((short) 1);
        user.setScore(faker.number().randomNumber());
        user.setAccountBalance(faker.number().randomDouble(2, 0, 10000));
        user.setSalary(new BigDecimal(faker.number().randomDouble(2, 3000, 50000))
                .setScale(2, RoundingMode.DOWN));
        user.setIsActive(new Random().nextBoolean());

        ComplexUser.UserStatus[] statuses = ComplexUser.UserStatus.values();
        user.setStatus(statuses[new Random().nextInt(statuses.length)]);
        user.setBirthday(faker.date().birthday());
        user.setAvatar("binary_avatar_data".getBytes(StandardCharsets.UTF_8));
        user.setDescription(faker.lorem().paragraph());
        user.setIgnoredData("This should be transient");
        user.setSpecificColumn("SpecificCol_Val");
        user.setSecretContent(faker.internet().password());

        ExtInfo extInfo = new ExtInfo();
        extInfo.setHobby(faker.esports().game());
        extInfo.setRemark("Generated by generic factory for delete test");
        user.setExtInfo(extInfo);

        user.setDepartmentId(UUID.randomUUID().toString().replaceAll("-", ""));
        return user;
    }

    private List<ComplexUser> buildComplexUsers(int count) {
        List<ComplexUser> users = new LinkedList<>();
        for (int i = 0; i < count; i++) {
            users.add(this.buildComplexUser());
        }
        return users;
    }

    private String insertAndGetComplexUserId() {
        ComplexUser user = this.buildComplexUser();
        this.sqlSession.getMapper(ComplexUserMapper.class).insert(user);
        this.sqlSession.commit();
        return user.getId();
    }

    private List<String> insertAndGetComplexUserIds(int count) {
        List<ComplexUser> users = this.buildComplexUsers(count);
        this.sqlSession.getMapper(ComplexUserMapper.class).batchInsert(users);
        this.sqlSession.commit();
        List<String> ids = new LinkedList<>();
        for (ComplexUser user : users) {
            ids.add(user.getId());
        }
        return ids;
    }

    // ==========================================
    // ComplexUserMapper (EzBaseMapper) Tests
    // ==========================================

    @Test
    public void ezBaseMapperDelete() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).delete(user);
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("ezBaseMapperDelete deleted {} records", ret);
    }

    @Test
    public void ezBaseMapperDeleteByTable() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).deleteByTable(EntityTable.of(ComplexUser.class), user);
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("ezBaseMapperDeleteByTable deleted {} records", ret);
    }

    @Test
    public void ezBaseMapperBatchDelete() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (String id : ids) {
            ComplexUser user = new ComplexUser();
            user.setId(id);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).batchDelete(users);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("ezBaseMapperBatchDelete deleted {} records", ret);
    }

    @Test
    public void ezBaseMapperBatchDeleteByTable() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (String id : ids) {
            ComplexUser user = new ComplexUser();
            user.setId(id);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).batchDeleteByTable(EntityTable.of(ComplexUser.class), users);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("ezBaseMapperBatchDeleteByTable deleted {} records", ret);
    }

    @Test
    public void ezBaseMapperDeleteById() {
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class)
                .deleteById(this.insertAndGetComplexUserId());
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("ezBaseMapperDeleteById deleted {} records", ret);
    }

    @Test
    public void ezBaseMapperDeleteByTableAndId() {
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class)
                .deleteByTableAndId(EntityTable.of(ComplexUser.class), this.insertAndGetComplexUserId());
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("ezBaseMapperDeleteByTableAndId deleted {} records", ret);
    }

    @Test
    public void ezBaseMapperBatchDeleteById() {
        List<String> userIds = this.insertAndGetComplexUserIds(2);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).batchDeleteById(userIds);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("ezBaseMapperBatchDeleteById deleted {} records", ret);
    }

    @Test
    public void ezBaseMapperBatchDeleteByTableAndId() {
        List<String> userIds = this.insertAndGetComplexUserIds(2);
        int ret = this.sqlSession.getMapper(ComplexUserMapper.class).batchDeleteByTableAndId(EntityTable.of(ComplexUser.class), userIds);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("ezBaseMapperBatchDeleteByTableAndId deleted {} records", ret);
    }

    // ==========================================
    // EzMapper Tests
    // ==========================================

    @Test
    public void ezMapperDelete() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        int ret = this.sqlSession.getMapper(EzMapper.class).delete(user);
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("ezMapperDelete deleted {} records", ret);
    }

    @Test
    public void ezMapperDeleteByTable() {
        String id = this.insertAndGetComplexUserId();
        ComplexUser user = new ComplexUser();
        user.setId(id);
        int ret = this.sqlSession.getMapper(EzMapper.class).deleteByTable(EntityTable.of(ComplexUser.class), user);
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("ezMapperDeleteByTable deleted {} records", ret);
    }

    @Test
    public void ezMapperBatchDelete() {
        List<String> ids = this.insertAndGetComplexUserIds(2);
        List<ComplexUser> users = new LinkedList<>();
        for (String id : ids) {
            ComplexUser user = new ComplexUser();
            user.setId(id);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(EzMapper.class).batchDelete(users);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("ezMapperBatchDelete deleted {} records", ret);
    }

    @Test
    public void ezMapperBatchDeleteByTable() {
        List<String> ids = this.insertAndGetComplexUserIds(3);
        List<ComplexUser> users = new LinkedList<>();
        for (String id : ids) {
            ComplexUser user = new ComplexUser();
            user.setId(id);
            users.add(user);
        }
        int ret = this.sqlSession.getMapper(EzMapper.class).batchDeleteByTable(EntityTable.of(ComplexUser.class), users);
        this.sqlSession.commit();
        Assert.assertEquals(3, ret);
        log.info("ezMapperBatchDeleteByTable deleted {} records", ret);
    }

    @Test
    public void ezMapperDeleteById() {
        int ret = this.sqlSession.getMapper(EzMapper.class)
                .deleteById(ComplexUser.class, this.insertAndGetComplexUserId());
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("ezMapperDeleteById deleted {} records", ret);
    }

    @Test
    public void ezMapperDeleteByTableAndId() {
        int ret = this.sqlSession.getMapper(EzMapper.class)
                .deleteByTableAndId(EntityTable.of(ComplexUser.class), ComplexUser.class, this.insertAndGetComplexUserId());
        this.sqlSession.commit();
        Assert.assertEquals(1, ret);
        log.info("ezMapperDeleteByTableAndId deleted {} records", ret);
    }

    @Test
    public void ezMapperBatchDeleteById() {
        List<String> userIds = this.insertAndGetComplexUserIds(2);
        // 原测试包含 null 验证批处理过滤
        userIds.add(null);
        int ret = this.sqlSession.getMapper(EzMapper.class).batchDeleteById(ComplexUser.class, userIds);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("ezMapperBatchDeleteById deleted {} records", ret);
    }

    @Test
    public void ezMapperBatchDeleteByTableAndId() {
        List<String> userIds = this.insertAndGetComplexUserIds(2);
        int ret = this.sqlSession.getMapper(EzMapper.class).batchDeleteByTableAndId(EntityTable.of(ComplexUser.class),
                ComplexUser.class, userIds);
        this.sqlSession.commit();
        Assert.assertEquals(2, ret);
        log.info("ezMapperBatchDeleteByTableAndId deleted {} records", ret);
    }

    // ==========================================
    // EzDelete DSL + JOIN Tests
    // ==========================================

    @Test
    public void ezDelete() {
        ComplexDepartment dept = new ComplexDepartment();
        dept.setName("Test_Dept_For_Delete");
        this.sqlSession.getMapper(EzMapper.class).insert(dept);

        ComplexUser user = this.buildComplexUser();
        user.setDepartmentId(dept.getId());
        this.sqlSession.getMapper(ComplexUserMapper.class).insert(user);
        this.sqlSession.commit();

        EntityTable userTable = EntityTable.of(ComplexUser.class);
        EntityTable deptTable = EntityTable.of(ComplexDepartment.class);

        EzDelete delete = EzDelete.delete(userTable).delete(deptTable)
                .join(deptTable, e ->
                        e.addCondition(userTable.field(ComplexUser.Fields.departmentId)
                                .eq(deptTable.field(BaseEntity.Fields.id))))
                .where(e ->
                        e.addCondition(userTable.field(BaseEntity.Fields.id).eq(user.getId())))
                .build();
        int ret = this.sqlSession.getMapper(EzMapper.class).ezDelete(delete);
        this.sqlSession.commit();
        Assert.assertTrue(ret >= 0);
        log.info("Test ezDelete - Deleted {} records using JOIN", ret);
    }

    @Test
    public void ezDeleteLambdaDsl() {
        ComplexOrder order = new ComplexOrder();
        order.setOrderNo("Del-Test-" + System.currentTimeMillis());
        order.setTotalAmount(new BigDecimal("100.00"));
        this.sqlSession.getMapper(EzMapper.class).insert(order);

        EntityTable itemTable = EntityTable.of(ComplexOrderItem.class);
        EzDelete delete = EzDelete.delete(itemTable)
                .where(w ->
                        w.addCondition(itemTable.field(ComplexOrderItem.Fields.orderId).eq(order.getId())))
                .build();

        int ret = this.sqlSession.getMapper(EzMapper.class).ezDelete(delete);
        this.sqlSession.commit();
        Assert.assertTrue(ret >= 0);
        log.info("Test ezDeleteLambdaDsl - Deleted {} records", ret);
    }

    @Test
    public void ezBatchDelete() {
        List<EzDelete> deletes = new LinkedList<>();
        List<String> ids = this.insertAndGetComplexUserIds(2);
        EntityTable userTable = EntityTable.of(ComplexUser.class);

        EzDelete delete1 = EzDelete.delete(userTable)
                .where(e -> e.addCondition(userTable.field(BaseEntity.Fields.id).eq(ids.get(0))))
                .build();
        deletes.add(delete1);

        EzDelete delete2 = EzDelete.delete(userTable)
                .where(e -> e.addCondition(userTable.field(BaseEntity.Fields.id).eq(ids.get(1))))
                .build();
        deletes.add(delete2);

        this.sqlSession.getMapper(EzMapper.class).ezBatchDelete(deletes);
        this.sqlSession.commit();
        log.info("Test ezBatchDelete completed");
    }

    @Test
    public void ezMapperDeleteBySql() {
        String id = this.insertAndGetComplexUserId();
        Map<String, Object> param = new HashMap<>();
        param.put("id", id);
        String realSql = "DELETE FROM ez_complex_user WHERE id = #{id}";
        try {
            int ret = this.sqlSession.getMapper(EzMapper.class).deleteBySql(realSql, param);
            this.sqlSession.commit();
            Assert.assertEquals(1, ret);
            log.info("Test ezMapperDeleteBySql result: {}", ret);
        } catch (Exception e) {
            log.error("Test ezMapperDeleteBySql exception", e);
            throw e;
        }
    }
}

